### ISSUE TITLE
Use LayoutKit

### ISSUE THREAD

**Issue by bitigchi** [smallstepforman/Medo#17]
Although it's not noticeable on the main window, dialogs and secondary windows look pretty out of place/alignment. Using Haiku LayoutKit would ensure the best native look for Medo.

Not the most important thing, but would be nice to have nevertheless.

**Comment by smallstepforman** [comment]
Hi bitigchi.  Thanks for the feedback.  Yes, you've correctly determined that the Editor Window cannot use the BLayoutKit due to the various modes.  However, the Effects Window and Export Window can transition to the LayoutKit.  The problem I have for the Effects Window  is that there are a several custom GUI widgets  (see the Gui directory) which I sourced from various places on the net, which are not BLayout aware so they'd all have to be modified.   This is a time consuming task, and I'm hoping that eventually the set of native widgets will be expanded to become viable replacements of the custom ones I'm using.  Until then, the EffectsWindow classes do use be_plain_font size to determine the layout of some elements, and works with font sizes up to 24.  

This leaves the Export Window as a candidate for BLayoutKit, and internally it has it's own code for positioning the widgets based on be_plain_font size.

Medo is primarily designed to be used on 4K screens, and looks really well at this size (and 20px font size).  However, 12-14px size on smaller 1366x720 monitors is problematic, and the layout kit would help here.

Thanks for the feedback.
