### ISSUE TITLE
Settings dialog: various drawing and layout artifacts

### ISSUE THREAD

**Issue by X547** [smallstepforman/Medo#7]
This is Medo-R1.0.0~Beta1-1.x86_64.hpkg \
Haiku hrev54776.

Problems:
1. Dialog background has white color, not system dialog background color.
2. Tab drawing glitches on resize.
3. View size in tab become wrong after switching tabs and window resize.

See my HaikuUtils ([Users](https://github.com/X547/HaikuUtils/tree/master/Users), [SystemManager](https://github.com/X547/HaikuUtils/tree/master/SystemManager)) for reference how to use Layout API.

![MedoSettings](https://user-images.githubusercontent.com/45505339/103042239-4ba1df80-45bc-11eb-9d2c-d612816e8176.png)

**Comment by bitigchi** [comment]
+1 on Layout API. All additional windows have misaligned labels and checkboxes and everything is spread around.

On 1440x900 resolution nearly all windows are bigger than the screen height itself.

**Comment by smallstepforman** [comment]
This one should be easy to fix, the tab views needs to receive resize events.  I missed this issue since the settings window was quickly created 3 days before release to allow the user to switch languages.  And yes, this will probably be the first window to be a candidate to learn how the BLayout api works.

**Comment by smallstepforman** [comment]
Fixed.  It's interesting that the BTabView doesn't automatically send ResizeTo (or FrameResized) to the non selected tabs, only the selected BTab.   Thanks for reporting the issue, and happy holidays.
